# Generated by Django 4.2.2 on 2023-07-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_menuitems_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitems',
            unique_together={('title', 'category')},
        ),
    ]
